#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

while ! pg_isready; do
  echo -n '.'
  sleep 1
done

cat >/var/lib/postgresql/data/pg_hba.conf <<EOL
local  all  all                trust
host   all  all  0.0.0.0/0     md5
host   all  all  127.0.0.1/32  trust
host   all  all  ::1/128       trust
host   all  all  all           trust
EOL

psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
    CREATE DATABASE "$1";
EOSQL
